name = "wildcat-be"
main = "src/index.ts"
compatibility_date = "2024-02-21"
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "api.wildcat2026.com"
custom_domain = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "9037a7b995d2405e888770a264c2d2f5"
localConnectionString = "postgresql://postgres.kqrvdcjjkljhiywnjcal:WkRoXiOMZDQrUety@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"

# Secrets are set via `npx wrangler secret put` command and should not be hardcoded in this file
# They will be injected at runtime from Cloudflare's secret management system